version: "3"
services:
  elm:
    image: codesimple/elm:0.18
    ports:
      - "8000:8000"
    command: reactor -a 0.0.0.0
    volumes:
      - ".:/code"
    working_dir: /code
    environment:
      - HOME=/tmp
