version: "3"
services:
  elm:
    build: .
    ports:
      - "8000:8000"
    command: reactor -a 0.0.0.0
    volumes:
      - ".:/code"
      - "package-cache:/tmp/.elm-install"
    working_dir: /code
    environment:
      - HOME=/tmp

volumes:
  package-cache:
    driver: local